film:
    path:     /
    defaults: { _controller: FilmBundle:Default:homepage }

acteur_ajout:
    path:     /acteur/ajout
    defaults: { _controller: FilmBundle:Acteur:ajout }
acteur:
    path:     /acteur
    defaults: { _controller: FilmBundle:Acteur:affiche }
acteur_modif:
    path:     /acteur/modif/{id}
    defaults: { _controller: FilmBundle:Acteur:modifier }
acteur_supp:
    path:     /acteur/supp/{id}
    defaults: { _controller: FilmBundle:Acteur:supprimer }
